# Path: .github/workflows/ci.yml
name: CI Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run code format check
        run: dotnet format --check

      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger trx --results-directory testResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: testResults 